### PR TITLE
Math Magicians - Events

### PR DESCRIPTION
**Pull request by Draxeytina**
- [x] Copy the files calculate.js and operate.js into a logic/ directory in your project.
- [x] Add big.js.
- [x] Import the files in the Calculator component.
- [x] Implement the event handlers in the component.

### CODE REVIEW

**Review by AmaduKamara — APPROVED** [review]
# Status: Approved 🟢🟢🟢 

Hi @Draxeytina,

YesYouAreGIF

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights

✔️ Correct use of Gitflow
✔️ No linter error
✔️ Good commit messages
✔️ README is okay
✔️ App works fine

## Recommendation

- [x] It would be nice if you could make the calculator app much bigger on the screen. It feels like a small mobile app right now. Since this is a web app, it would be great to make it a bit larger 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Draxeytina** [comment]
> # Status: Approved 🟢🟢🟢
> Hi @Draxeytina,
> 
> YesYouAreGIF [ ](https://user-images.githubusercontent.com/50941074/176785103-062d989a-cd1f-4fff-b561-27df5bd5d8bd.gif) YesYouAreGIF [ ](https://user-images.githubusercontent.com/50941074/176785103-062d989a-cd1f-4fff-b561-27df5bd5d8bd.gif)
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it: ship it: Congratulations! 🎉
> 
> ## Highlights
> ✔️ Correct use of Gitflow ✔️ No linter error ✔️ Good commit messages ✔️ README is okay ✔️ App works fine
> 
> ## Recommendation
> * [x]  It would be nice if you could make the calculator app much bigger on the screen. It feels like a small mobile app right now. Since this is a web app, it would be great to make it a bit larger 👍
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @AmaduKamara! Yeah that's a valid suggestion let me increase the size

**Comment by AmaduKamara** [comment]
Great 👍

**Comment by AmaduKamara** [comment]
You can merge your project and submit it on your dashboard.

**Pull request merged**
